version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: school_vehicle_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - school_network
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    container_name: school_vehicle_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - school_network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: school_vehicle_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: school_vehicle_management
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: school_user
      MYSQL_PASSWORD: school_password
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    networks:
      - school_network

  redis:
    image: redis:alpine
    container_name: school_vehicle_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - school_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: school_vehicle_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root_password
    ports:
      - "8080:80"
    networks:
      - school_network
    depends_on:
      - db

volumes:
  db_data:
  redis_data:

networks:
  school_network:
    driver: bridge
